### PR TITLE
Mobile fix: 1. Remove horizontal scrolling 2. Responsive frontpage lo…

### PR DESCRIPTION
**Pull request by daniel-lengyel**
…go 3. Responsive introduction section 4. Add padding to anchor points of sections 5. Responsive footer

### CODE REVIEW

**Comment by justelad** [comment]
@daniel-lengyel can you please resolve the conflicts?

**Comment by daniel-lengyel** [comment]
@justelad the conflicts are resolved now.

**Comment by daniel-lengyel** [comment]
Hey Elad, 
could you please tell us the size of your screen? We tested the side with x-code, safari-responsive-modus, on iPhone5, Samsung Galaxy Edge S7, S8, MacBookPro 15“ and iMac 27“. Of course we don´t have every hardware here to test and x-code as well as safari-rsponsive-design sometimes don´t show up the complete truth…..

Thanks forward,
Dani and Marco

**Comment by justelad** [comment]
hi @daniel-lengyel,
i have a Retina, 13-inch screen with 2560 x 1600 pixels

**Comment by justelad** [comment]
@daniel-lengyel thanks for pushing all of the changes. it looks so much better!
a couple of really last things:
- [ ] the section where it says `Fault Tolerant`, `Censorship Resistant` etc - I think that the entire section is center-aligned but it should fill the enclosing `div`
- [ ] on `The talks from the 2017 Swarm Orange Summit can be found at swarm-orange-summit.eth` - the link at the end of the sentence should point to: `https://swarm-gateways.net/bzz:/swarm-orange-summit.eth/`
- [ ] below the headers in `Talks` and `Online Press` there are double horizontal separators
- [ ] below `Contact information` there's a horizontal seperator but i dont think it's necessary

Thanks a lot 🙏

**Comment by nonsense** [comment]
@justelad since you merged this, please coordinate with @homotopycolimit to update ENS, so that https://ethersphere.github.io/swarm-home/ is the same as https://swarm-gateways.net/bzz:/theswarm.eth/

**Comment by homotopycolimit** [comment]
Has this been uploaded to swarm yet? Do you have updated content hashes for me? (@justelad)

**Comment by nonsense** [comment]
@homotopycolimit the content has been uploaded to Swarm.

@skylenet added automatic deployment to our website releases, so now every time we tag a release of the website, it gets uploaded to Swarm and released under Github.

We should update ENS to reflect the current master version soon.

@justelad are you happy with the current version, or we are waiting for more fixes? If we are not waiting for fixes, we should update ENS, and think about what should be next steps to keep the website up-to-date.

**Comment by homotopycolimit** [comment]
I will update ENS entry as soon as I have the content hash. just let me know.

**Comment by justelad** [comment]
@nonsense I think this is good to go as it is. Would be nice to put some info about swarm summit but I don’t have the bandwidth for this

**Pull request merged**
